basePath: /
definitions:
  api.AuditResult:
    properties:
      DisplayValue:
        type: string
      description:
        type: string
      id:
        type: string
      numericUnit:
        type: string
      numericValue:
        type: number
      score:
        type: number
      scoreDisplayMode:
        type: string
      title:
        type: string
    type: object
  api.Report:
    properties:
      audit_results:
        additionalProperties:
          $ref: '#/definitions/api.AuditResult'
        type: object
      created_at:
        type: string
      form_factor:
        example: desktop
        type: string
      id:
        type: string
      performance_score:
        type: number
      raw_json:
        type: string
      throughput_kbps:
        example: 50000
        type: integer
      url:
        type: string
    type: object
  api.ReportRequest:
    properties:
      form_factor:
        example: desktop
        type: string
      throughput_kbps:
        example: 50000
        type: integer
      url:
        example: https://www.google.com
        type: string
    type: object
info:
  contact: {}
  description: Run lighthouse as a service
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Websu API
  version: "1.0"
paths:
  /reports:
    post:
      consumes:
      - application/json
      description: |-
        Run a lighthouse audit to generate a report. The field `raw_json` contains the
        JSON output returned from lighthouse as a string. Note that `raw_json` field is
        only returned during initial creation of the report.
      parameters:
      - description: Lighthouse parameters to generate the report
        in: body
        name: ReportRequest
        required: true
        schema:
          $ref: '#/definitions/api.ReportRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/api.Report'
            type: array
      summary: Create a Lighthouse Report
swagger: "2.0"
