basePath: /
definitions:
  api.AuditResult:
    properties:
      DisplayValue:
        type: string
      description:
        type: string
      id:
        type: string
      numericUnit:
        type: string
      numericValue:
        type: number
      score:
        type: number
      scoreDisplayMode:
        type: string
      title:
        type: string
    type: object
  api.Location:
    properties:
      address:
        example: 8.8.8.8:50051
        type: string
      created_at:
        type: string
      display_name:
        example: Sydney, AU
        type: string
      id:
        type: string
      name:
        description: TODO Add unique constraint to Name
        example: australia-southeast1
        type: string
      order:
        type: integer
      secure:
        description: Flag to indicate whether TLS should be used
        type: boolean
    type: object
  api.Report:
    properties:
      audit_results:
        additionalProperties:
          $ref: '#/definitions/api.AuditResult'
        type: object
      created_at:
        type: string
      form_factor:
        example: desktop
        type: string
      id:
        type: string
      performance_score:
        type: number
      raw_json:
        type: string
      throughput_kbps:
        example: 50000
        type: integer
      url:
        type: string
    type: object
  api.ReportRequest:
    properties:
      form_factor:
        example: desktop
        type: string
      location:
        example: australia-southeast1
        type: string
      throughput_kbps:
        example: 50000
        type: integer
      url:
        example: https://www.google.com
        type: string
    type: object
info:
  contact: {}
  description: Run lighthouse as a service
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Websu API
  version: "1.0"
paths:
  /reports:
    post:
      consumes:
      - application/json
      description: Add a new location from which reports can be generated
      parameters:
      - description: Details of the new location
        in: body
        name: Location
        required: true
        schema:
          $ref: '#/definitions/api.Location'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/api.Location'
            type: array
      summary: Add a new location
swagger: "2.0"
