name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
    - name: go test ./...
      run: |
          sudo npm install -g lighthouse
          go test ./...
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push websu-api
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./build/Dockerfile_websu-api
        platforms: linux/amd64,linux/arm64,linux/386
        push: true
        tags: samos123/websu-api:latest
    - name: Build and push lighthouse-server
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./build/Dockerfile_lighthouse-server
        platforms: linux/amd64,linux/arm64,linux/386
        push: true
        tags: samos123/lighthouse-server:latest
